### ISSUE TITLE
Printer setting software unavailable.

### ISSUE THREAD

**Issue by marssystems** [cos-it-is/TheBAT#1]
The printer setting software is unavailable from the readme.md file.

[Programming the Thermal Printer:](https://github.com/cos-it-is/TheBAT#programming-the-thermal-printer)
Start by downloading the printer setting software available here .

**Comment by cos-it-is** [comment]
Hey - Yes, I am preparing an update to the repo, with added features also.

I will work more on the readme as it is not very clear.

**Comment by marssystems** [comment]
OK - looking forward to it !

**Comment by cos-it-is** [comment]
https://www.hsprinter.com/?m=common&a=down&name=639a91a94e329.zip&g=e

**Comment by marssystems** [comment]
Thanks!
